name: meshwork
services:
  backend:
    build: ./meshwork/backend_rs
    ports:
      - "8000:8000"
  frontend:
    build: ./meshwork/frontend/webapp
    ports:
      - "3000:3000"
    depends_on:
      - backend
  neo4j:
    image: neo4j:latest
    volumes:
      - /$HOME/neo4j/logs:/logs
      - /$HOME/neo4j/config:/config
      - /$HOME/neo4j/data:/data
      - /$HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/your_password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

networks:
  default:
